name             'nagios-nodes'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures nagios-nodes'
long_description 'Installs/Configures nagios-nodes'
version          '0.1.0'
